Reference pix payment method
uphold/topper-docs pull request #37
Opened 2024-02-07 15:42 UTC by joaobaptistanqda

### Description

This PR adds info for pix payment method

### Related issues

https://uphold.atlassian.net/browse/SWY-1489

2024-03-28 17:00 UTC, zangetsouu submitted a review, later dismissed

2024-05-08 22:21 UTC, andregoncalvesdev requested changes

2024-05-08 22:21 UTC, andregoncalvesdev commented on docs/digital-wallets.md
> +| Browser | Scenario | Apple Pay | Google Pay | Pix |
The changes on this file we can revert. PIX is not a digital wallet. And it is supported on every scenario like cards.

We need to improve instead the `Environments` section with sandbox testing amounts.

2024-05-10 09:15 UTC, jackmurdoch approved these changes

2024-05-14 11:23 UTC, jackmurdoch approved these changes

2024-05-15 16:11 UTC, merged